# NB: don't set `language: haskell` here

# See also https://github.com/hvr/multi-ghc-travis for more information
notifications:
  email:
    - sam.ellard@gmail.com

branches:
  only:
    - source

env:
  global:
    - secure: uBFGVYMKELBVEjb5Y6OlRFQrW6y2BGRg2vJTzw3wLPKGWaZQ89PBk4MMFKqhVnQROA/Q4j+LEYu/H/aM2CR2UjAPqNC6ubSiHNnoq/VuS2tJ6YnOZDZfbrrXiFCKLhBi8o17qJml18+4Q+Nr2/pZo2/O+jhp/ADpfWXYBBI9EoU=
    - secure: "p7gBzSHIYKLb8CS3dcAQ3uIGszeYzy+Jcys0IsxUAPH3ejzHV84a4Gq4TlvDSj6mK8+wAUPi38avrQE66Wy/PxL+5zGZfbqd9PlEKgHP1XvwxeZEg9j7Lt5mlou6sTMnglW67JztcdVe5n21m1wzd+IzvACp1qqJB7MFXYPD+/4="
    - secure: "PXntq20v7BwrE8dzjCN5ZHka94zXE96Z5hGwEph94JQqPGpvwSuB4xsMAz+3TBn/FYitVA89qZA8d1qDkKqdf9ssG9+rZnt79WQJluM67MxlkQx3PKjxiBjAuoRTl8yRCflMLRb4TOfcMgAN4PoW5PxToiR0423u2Q90tRJAczM="

  matrix:
    - CABALVER=1.20 GHCVER=7.8.3
#    - CABALVER=1.22 GHCVER=7.10.1
#    - CABALVER=head GHCVER=head

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

  - git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'

install:
  - travis_retry cabal update
  - cabal sandbox init
  - cabal install --only-dependencies --disable-documentation
  - cabal configure --disable-library-profiling --disable-tests --disable-library-coverage --disable-benchmarks --disable-split-objs

before_script:
  - git config --global user.name "$GH_NAME"
  - git config --global user.email "$GH_EMAIL"

script:
  - cabal run -j build

after_success:
  - if [[ "$TRAVIS_BRANCH" == "source" ]]; then
    cd _site;
    export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///');
    git remote add github https://redllamas:${GH_TOKEN}@${REMOTE};
    git add --all;
    git status;
    git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )";
    git push github master:master | grep -v http;
    fi