branches:
  only:
  - source
  matrix:
  - CABALVER=1.20 GHCVER=7.8.3
before_install:
- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README
  | grep -v CNAME | xargs -r git rm'
install:
- travis_retry cabal update
- cabal sandbox init
- cabal install --only-dependencies --disable-documentation
- cabal configure --disable-library-profiling --disable-tests --disable-library-coverage
  --disable-benchmarks --disable-split-objs
before_script:
- git config --global user.name "redllamas"
- git config --global user.email "sam.ellard@gmail.com"
script:
- cabal run -j build
after_success:
- if [[ "$TRAVIS_BRANCH" == "source" ]]; then cd _site; export REMOTE=$(git config
  remote.origin.url | sed 's/.*:\/\///'); git remote add github https://${GH_TOKEN}@${REMOTE};
  git add --all; git status; git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER
  )"; git push github master:master | grep -v http; fi
GH_TOKEN:
  secure: Npoh5cs55HkjhanWF2wHnf7VvHGZMwewJ4O24hegnuK+/Y5L4TiloUJQaj871MaG1gNekQ/0+lV67VBGNDU3wK3hyjQ9JbRobnpT2wzzqTdJ50r4hoPfCVK2xA/FsMm7AqbrVewKtQmKw2xfrJPtGng4PwVBIqmJlif5AJEcN9Y=
GH_EMAIL:
  secure: NazKaLr1rGW1f2yQ7ehfNnTKu0JNauv8U9jk+l5hID+bdQae14VFbtaFqLJuDYDQKy6c7DobzVlGwdLB8sN02cf3xl+dsl6cMEBLknoMze/VttRox7Q+tJSpgOfi0IGi/l+9GffjUaVSWhDvZIzYGiP8O9RYIFp5dNyZjBZC368=
GH_NAME:
  secure: guBfEAFGptI31Ozr/9lK0MuKGGiDokjYe3xBO+F7s7IV90JzNfRbiHLWs0BrFEkILK7PpAjB+SBljW3H3X6dLXED0ogfsu38RcxdIVMSFrO1InuVdbG3pNyuGlhePbKoeBz/T2C4aa7CdiGWUDWfq3U72PbUosG2sMkaD0TsOT8=
